# Generated by Django 3.2 on 2021-05-03 11:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Computerspiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('beschreibung', models.TextField(max_length=500)),
                ('developer_studio', models.CharField(max_length=100)),
                ('date_released', models.DateTimeField(blank=True, default=datetime.date.today)),
                ('genre', models.CharField(choices=[('FPS', 'First-Person Shooter'), ('RPG', 'Role-Playing Game'), ('FG', 'Fighting Game'), ('RG', 'Racing Game'), ('SIM', 'Simulation'), ('TD', 'Tower Defense')], max_length=10)),
                ('ersteller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', related_query_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Computerspiel',
                'verbose_name_plural': 'Computerspiele',
                'ordering': ['name', '-genre'],
            },
        ),
    ]
