# Generated by Django 3.2 on 2021-05-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Computerspiele', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerspiel',
            name='fsk',
            field=models.CharField(choices=[('0', 'ab 0'), ('6', 'ab 6'), ('12', 'ab 12'), ('16', 'ab 16'), ('18', 'ab 18')], default='0', max_length=10),
        ),
    ]
